## Handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

### 1. Up Sampling

In [12]:
import pandas as pd 
import numpy as np

# set the random seed for reproductivity 
np.random.seed(123)

# create a dataframe with 2 classes 
n_samples=1000
n_class_0_ratio=0.9

n_class_0=int(n_samples * n_class_0_ratio)
n_class_1=n_samples-n_class_0

In [13]:
n_class_0,n_class_1

(900, 100)

In [14]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET

class_0=pd.DataFrame({
    'feacture_1':np.random.normal(loc=0, scale=1, size=n_class_0),
    'feacture_2':np.random.normal(loc=1,scale=1, size=n_class_0),
    'target':[0]*n_class_0
})

class_1 = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [15]:
class_1,class_0

(    feature_1  feature_2  target
 0    1.699768   2.139033       1
 1    1.367739   2.025577       1
 2    1.795683   1.803557       1
 3    2.213696   3.312255       1
 4    3.033878   3.187417       1
 ..        ...        ...     ...
 95   1.376371   2.845701       1
 96   2.239810   0.880077       1
 97   1.131760   1.640703       1
 98   2.902006   0.390305       1
 99   2.697490   2.013570       1

 [100 rows x 3 columns],
      feacture_1  feacture_2  target
 0     -1.085631    1.551302       0
 1      0.997345    1.419589       0
 2      0.282978    2.815652       0
 3     -1.506295    0.747250       0
 4     -0.578600    0.707996       0
 ..          ...         ...     ...
 895    0.238761    0.996845       0
 896   -1.106386    0.569340       0
 897    0.366732    0.853584       0
 898    1.023906    2.160176       0
 899   -0.210056    0.358488       0

 [900 rows x 3 columns])

In [16]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [17]:
df.head(904)
# df.tail()

     feacture_1  feacture_2  target  feature_1  feature_2
0     -1.085631    1.551302       0        NaN        NaN
1      0.997345    1.419589       0        NaN        NaN
2      0.282978    2.815652       0        NaN        NaN
3     -1.506295    0.747250       0        NaN        NaN
4     -0.578600    0.707996       0        NaN        NaN
..          ...         ...     ...        ...        ...
899   -0.210056    0.358488       0        NaN        NaN
900         NaN         NaN       1   1.699768   2.139033
901         NaN         NaN       1   1.367739   2.025577
902         NaN         NaN       1   1.795683   1.803557
903         NaN         NaN       1   2.213696   3.312255

[904 rows x 5 columns]

In [18]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [19]:
## upsampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [21]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample With replacement
         n_samples=len(df_majority),
         random_state=42
        )

In [28]:
df_minority.shape   #(100,5)
df_minority_upsampled.shape   #(900,5)

(900, 5)

In [29]:
df_minority_upsampled.head()

     feacture_1  feacture_2  target  feature_1  feature_2
951         NaN         NaN       1   1.125854   1.843917
992         NaN         NaN       1   2.196570   1.397425
914         NaN         NaN       1   1.932170   2.998053
971         NaN         NaN       1   2.272825   3.034197
960         NaN         NaN       1   2.870056   1.550485

In [31]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [32]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64