pandas for data analysis in Python:
===
pandas is a powerful library for data manipulation and analysis. It provides two main data structures: Series (1D) and DataFrame (2D). With pandas, you can easily load, clean, explore, and visualize data. It offers a wide range of functions for filtering, grouping, and summarizing data, making it an essential tool for any data analyst or scientist working in Python.

serires:
===
A Series is a one-dimensional labeled array that can hold any data type. It consists of two main components: the index and the values. The index is a set of labels that uniquely identifies each element in the Series, while the values are the actual data stored in the Series. You can create a Series from a list, dictionary, or even a NumPy array. Series are useful for handling time series data, categorical data, or any situation where you want to associate labels with your data.

In [29]:
# series 
import pandas as pd 
import numpy as np

# ── Create a Series ──────────────────────────────
marks=pd.Series([2,3,4,5,6])
# print(marks)
# print(type(marks))

index=['a','c','f','s','r']
data=[3,4,5,6,7]
pd.Series(data,index=index)

score=pd.Series([4,5,6,7],index=['d','r','t','o'])
print(score)

score['d']
score.iloc[3]

# print(score['t'])

# score[score > 4]

# print(score.mean())

# Useful Series properties
score.values # underlying NumPy array
score.index    # Index(['Ali','Sara','Hamza','Ayesha','Usman'])
score.dtype    # int64
score.name     # None (you can set: marks.name = 'Score')

d    4
r    5
t    6
o    7
dtype: int64

Dataframe:
===
A DataFrame is a two-dimensional labeled data structure that can hold data of different types (e.g., integers, floats, strings). It is similar to a table in a relational database or an Excel spreadsheet. A DataFrame consists of rows and columns, where each column can be thought of as a Series. You can create a DataFrame from various sources such as dictionaries, lists, or even other DataFrames. DataFrames are ideal for handling structured data and performing operations like filtering, grouping, and merging datasets.

Createing a DataFrame from  dictionaries of lists:
===

In [36]:
import pandas as pd
df=pd.DataFrame({
    'name': ["M yousaf",'Ayesha','Ali','Ibrahim'],
    'age':[21,19,15,30],
    'education':['bs','matric','inter','ms'],
    'sex':['male','female','male','male'],
})
df

       name  age education     sex
0  M yousaf   21        bs    male
1    Ayesha   19    matric  female
2       Ali   15     inter    male
3   Ibrahim   30        ms    male

In [45]:
# ── Key properties ───────────────────────────────
df.shape
df.size
df.columns
df.dtypes
df.index

RangeIndex(start=0, stop=4, step=1)

In [50]:
# ── From a NumPy array ───────────────────────────
arr = np.random.randint(50, 100, (5, 3))
df2 = pd.DataFrame(arr, columns=['Math', 'Physics', 'CS'])
df2

   Math  Physics  CS
0    62       57  61
1    67       63  75
2    62       82  61
3    63       72  50
4    82       92  99

creating a dataframe from list of dictionaries:
=

In [60]:
df=pd.DataFrame([
    {'name':'yousaf','age':21,'gender':'mamle'},
    {'name':'yousaf2','age':41,'gender':'mamle'},
    {'name':'yousaf3','age':31,'gender':'mamle'}
])
df

      name  age gender
0   yousaf   21  mamle
1  yousaf2   41  mamle
2  yousaf3   31  mamle

Exercise 1
===

In [ ]:
# Build Your First DataFrame
# Create a Series of 7 daily temperatures (label them Mon–Sun). Find the max, min, and mean.
# Create a DataFrame of 5 products: Name, Price, Quantity, Category. Set Name as the index using .set_index('Name').
# Add a new column Total_Value = Price × Quantity.

In [ ]:
# Create a Series of 7 daily temperatures (label them Mon–Sun). Find the max, min, and mean.
temp=pd.Series([23,56,76,34,44,20,30],index=['mon','tue','wed','thu','fri','sat','sun'])
# print("temperture \n",temp)
print(temp.mean())
print(temp.max())
print(temp.min())

40.42857142857143
76
20

In [110]:
# Create a DataFrame of 5 products: Name, Price, Quantity, Category. Set Name as the index using .set_index('Name').
df=pd.DataFrame({
    'Name'       :['mobiles','laptops','Watch','shoes','car'],
    'price'      :[200000,230000,13909,43000,8000500],
    'Quantity'   :[2,4,5,6,1],
    'Category'   :['apple','dell','casio','nike','toyota'],
})
df
# Set 'Name' as index
df.set_index('Name', inplace=True)
# df
# # Add a new column Total_Value = Price × Quantity.
df['Total_Value']=df['price'] * df['Quantity']
df

           price  Quantity Category  Total_Value
Name
mobiles   200000         2    apple       400000
laptops   230000         4     dell       920000
Watch      13909         5    casio        69545
shoes      43000         6     nike       258000
car      8000500         1   toyota      8000500

loading data
===

In [24]:
# ── Reading CSV (most common) ─────────────────────
import pandas as pd

# data=pd.read_csv('data.csv',parse_dates=['Date'])
# data

# df = pd.read_csv('data.csv', index_col='id')         # use 'id' as index
df = pd.read_csv('data.csv', parse_dates=['Date'])    # auto-parse dates
df = pd.read_csv('data.csv', nrows=1000)              # only first 1000 rows
df = pd.read_csv('data.csv', usecols=['Category', 'Sales']) # only specific cols

df.head(4)

  Category  Sales
0        A  754.0
1        B  110.0
2        C  398.0
3        B  522.0

In [30]:
# ── Other formats ─────────────────────────────────
df=pd.read_excel('data.xlsx')
df

# df = pd.read_json('data.json')
# df = pd.read_parquet('data.parquet')  # fast columnar format

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [32]:
# ── Writing / exporting ───────────────────────────
df.to_csv('data.csv', index=False)    # index=False avoids extra col
df.to_excel('data.xlsx', index=False)

df4=pd.read_excel('data.xlsx')
df4

    Name  Age
0  Krish   32
1   Jack   34
2   John   31

In [36]:
# ── Quick inline DataFrame for testing ────────────
from io import StringIO

csv_text="""name,price,quantitiy
Apple,40,3
mango,54,7
banana,0.8,200"""
df=pd.read_csv(StringIO(csv_text))
df

     name  price  quantitiy
0   Apple   40.0          3
1   mango   54.0          7
2  banana    0.8        200

Exploring Your Data
===
Before you analyze, you must understand what you have. These are the first commands you run on any new dataset.

In [43]:
# Python — exploratory data analysis (EDA) commands

df=pd.read_csv('sales_data.csv')
# ── First look ────────────────────────────────────
df.head(5)         # first 5 rows
df.tail(5)         # last 5 rows
df.sample(10)      # 10 random rows (great for spotting issues)

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
74,10075,2024-03-15,Clothing,Tommy Hilfiger Polo Shirt,5,49.99,249.95,Asia,Debit Card
154,10155,2024-06-03,Beauty Products,GlamGlow Supermud Clearing Treatment,1,59.00,59.00,Europe,PayPal
44,10045,2024-02-14,Clothing,Patagonia Better Sweater,2,139.99,279.98,Asia,Debit Card
128,10129,2024-05-08,Clothing,Lululemon Align Leggings,3,98.00,294.00,Asia,Debit Card
90,10091,2024-03-31,Electronics,Logitech MX Master 3 Mouse,2,99.99,199.98,North America,Credit Card
84,10085,2024-03-25,Electronics,Ring Video Doorbell,1,99.99,99.99,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
9,10010,2024-01-10,Books,Dune by Frank Herbert,2,25.99,51.98,North America,Credit Card
55,10056,2024-02-25,Home Appliances,KitchenAid Artisan Stand Mixer,1,499.99,499.99,Europe,PayPal
19,10020,2024-01-20,Home Appliances,Ninja Professional Blender,1,99.99,99.99,Europe,PayPal

In [53]:
# ── Shape & structure ─────────────────────────────

df.shape  # (240, 9) — 240 rows, 9 columns
df.dtypes
# df.info()   # dtypes + non-null counts + memory usage — run this FIRST
# df.columns.to_list() #all column in list ['t id',....]

['Transaction ID',
 'Date',
 'Product Category',
 'Product Name',
 'Units Sold',
 'Unit Price',
 'Total Revenue',
 'Region',
 'Payment Method']

# statical summary

In [56]:
# statical summary
df.describe() #mean, medium,max,min,count  for numeric column

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [57]:
df.describe(include='all') # includes objects/catergoriacal colm

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
count,240.00000,240,240,240,240.000000,240.000000,240.000000,240,240
unique,NaN,240,6,232,NaN,NaN,NaN,3,3
top,NaN,2024-01-01,Electronics,Dyson Supersonic Hair Dryer,NaN,NaN,NaN,North America,Credit Card
freq,NaN,1,40,2,NaN,NaN,NaN,80,120
mean,10120.50000,NaN,NaN,NaN,2.158333,236.395583,335.699375,NaN,NaN
std,69.42622,NaN,NaN,NaN,1.322454,429.446695,485.804469,NaN,NaN
min,10001.00000,NaN,NaN,NaN,1.000000,6.500000,6.500000,NaN,NaN
25%,10060.75000,NaN,NaN,NaN,1.000000,29.500000,62.965000,NaN,NaN
50%,10120.50000,NaN,NaN,NaN,2.000000,89.990000,179.970000,NaN,NaN
75%,10180.25000,NaN,NaN,NaN,3.000000,249.990000,399.225000,NaN,NaN
max,10240.00000,NaN,NaN,NaN,10.000000,3899.990000,3899.990000,NaN,NaN

In [60]:
df.describe(percentiles=[.4,.5,.9]) #custom percentile

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
40%       10096.60000    1.000000    52.000000     129.594000
50%       10120.50000    2.000000    89.990000     179.970000
90%       10216.10000    4.000000   554.000000     754.989000
max       10240.00000   10.000000  3899.990000    3899.990000

Mising vlaues overview
===

In [1]:
import pandas as pd
df=pd.read_csv('sales1_data.csv')
df.isnull()   #count of null per column 
df.isnull().mean()*100 # % missing per column 
df.head(5)

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  South    NaN
4  2023-01-05  Product3  501.0   East

Unique values
===

In [95]:
df['Region'].unique()    # ['North','South','East','West']
df['Region'].nunique()   #4

df['Product'].value_counts()  #frequency of each product

Product
Product3    11
Product2     8
Product1     5
Name: count, dtype: int64

In [ ]:
df['Product'].value_counts(normalize=True)*100   ## as percentages

Product
Product3    45.833333
Product2    33.333333
Product1    20.833333
Name: proportion, dtype: float64

Correlation
===
Correlation is a statistical measure that describes the strength and direction of the relationship between two variables. In

In [7]:
# df[['Product','Region']].corr()

EDA on a Dataset
===
Create or download a CSV with at least 50 rows and 5 columns (or use any Kaggle dataset).

Run the full EDA checklist above. What dtypes are wrong? Which columns have nulls?
Find the top 3 most frequent values in a categorical column.
Find any columns where min or max looks suspiciously wrong (potential data errors).

In [18]:
import pandas as pd

df=pd.read_csv('salesKaggle_data.csv')
df.isnull()
df.dtypes
df.head(3)

df.describe()
# df.sample

,Product_ID,Sales_Amount,Quantity_Sold,Unit_Cost,Unit_Price,Discount
count,49.000000,49.000000,49.000000,49.000000,49.000000,49.000000
mean,1052.102041,4476.734490,24.795918,2617.499796,2851.349388,0.140204
std,28.362420,2539.855996,13.444298,1466.004294,1482.607298,0.085865
min,1002.000000,198.250000,1.000000,121.190000,267.220000,0.000000
25%,1024.000000,2749.170000,13.000000,1100.810000,1427.210000,0.060000
50%,1058.000000,4223.390000,23.000000,2543.360000,2869.600000,0.130000
75%,1075.000000,6483.840000,34.000000,3816.390000,4270.650000,0.200000
max,1100.000000,9638.640000,48.000000,4904.930000,5166.720000,0.300000

Selecting Data
==

In [23]:
df = pd.DataFrame({
    'Name':    ['Ali','Sara','Hamza','Ayesha','Usman'],
    'Math':    [85, 72, 55, 95, 40],
    'Physics': [76, 85, 60, 92, 38],
    'CS':      [95, 90, 70, 98, 45],
})
df

     Name  Math  Physics  CS
0     Ali    85       76  95
1    Sara    72       85  90
2   Hamza    55       60  70
3  Ayesha    95       92  98
4   Usman    40       38  45

In [28]:
# ── Column selection ─────────────────────────────
df['Math']               # single column → Series
df[['Math', 'CS']]      # multiple columns → DataFrame

   Math  CS
0    85  95
1    72  90
2    55  70
3    95  98
4    40  45

In [39]:
# ── .loc — label-based ───────────────────────────
df.loc[2]                 # row with index label 2 (Hamza's row)
df.loc[0:2]              # rows 0,1,2 — NOTE: loc is INCLUSIVE at end!
df.loc[0:2, 'Math':'CS']  # rows 0-2, cols Math through CS
df.loc[0, 'Physics']      # single cell: 76

np.int64(76)

In [45]:
# # ── .iloc — position-based ───────────────────────
df.iloc[0]                # first row
df.iloc[0:3]             # rows 0,1,2 — iloc is EXCLUSIVE at end (like Python slices)
df.iloc[:3, 1:3]          # first 3 rows, columns 1 and 2
df.iloc[-1]              # last row
df.iloc[:, :-1]          # all rows, all cols except last

     Name  Math  Physics
0     Ali    85       76
1    Sara    72       85
2   Hamza    55       60
3  Ayesha    95       92
4   Usman    40       38

In [48]:
# # ── at / iat — fast single-cell access ───────────
df.at[2, 'Math']          # 55 — fastest for single label access
df.iat[2, 1]              # 55 — fastest for single position access

np.int64(55)

In [52]:
# # ── Setting values ───────────────────────────────

df.loc[4, 'Math'] = 50    # correct a specific value
df.loc[4, ['Math','Physics','CS']] = [50, 42, 48]  # set multiple
df

     Name  Math  Physics  CS
0     Ali    85       76  95
1    Sara    72       85  90
2   Hamza    55       60  70
3  Ayesha    95       92  98
4   Usman    50       42  48

# Cleaning Messy Data
80% of real data science work is cleaning. Pandas is built for this.

Handling Missing Values (NaN)

Real data is almost always incomplete. NaN (Not a Number) is Pandas' representation of missing data. Handling it correctly is critical — wrong decisions here propagate errors through your entire analysis.

In [107]:
import seaborn as sns
df = sns.load_dataset('titanic')

df.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

# ── Detect ─────────

In [82]:

# df.isnull()               # True/False mask for every cell
df.isnull().sum()         # total nulls per column
# df.notnull()              # opposite
df[df['embark_town'].isnull()]  # rows where revenue is missing

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True

# ── Drop ───

In [105]:
df.dropna()              # drop any row with at least 1 NaN
#df
df.dropna(axis=1)         # drop any COLUMN with at least 1 NaN

df.dropna(subset='age')    # drop rows where 'age' is NaN
df.dropna(thresh=4).head(2)      # keep rows with at least 4 non-null values

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False

Fill
===

In [138]:
# df.fillna(0)                          # fill ALL NaN with 0
df['age'].fillna(df['age'].mean())      #fill with column mean 

df['embark_town'].fillna('Unknown')     # fill categorical with a label
df['age'].fillna('Unknown')

df.fillna(method='ffill')                # forward-fill (use previous value)

df.fillna(method='bfill').head(3)                 # backward-fill

# df.interpolate()                       # linear interpolation

C:\Users\Acer\AppData\Local\Temp\ipykernel_16188\901430406.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')                # forward-fill (use previous value)
C:\Users\Acer\AppData\Local\Temp\ipykernel_16188\901430406.py:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill').head(3)                 # backward-fill

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,C,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,C,Southampton,yes,True

In [144]:
# ── Fill different columns differently ────────────

df.fillna({'age': df['age'].median(),
           'region':  'Unknown',
           'units':   0
           }).head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

Fixing Data Types & Duplicates
===
After loading, columns often have wrong types. Dates come as strings, numbers as objects, booleans as 0/1. Fixing types is essential before any analysis.

In [ ]:
df.head(2)
df['date']=pd.to_datetime('today').strftime("%y-%m-%d")
print(df.dtypes['date'])
df.head(1)

df['embark_town']=

object

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,date
0,0,3,male,22.0,1,0,7.25,S,Third,man,True,NaN,Southampton,no,False,26-04-27

In [ ]:
# type conversion 
df['sibsp'].astype(float)

df['fare'].astype(int)

df['date']=pd.to_datetime(df['date'])
print(df.dtypes['date'])
df.head(2)

# convert to category 
df['who']=df['who'].astype('category')
df.head(1)

# when astype fail 
df['who']=pd.to_numeric(df['who'],errors='coerce')
df.head(2)

datetime64[ns]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,date
0,0,3,male,22.0,1,0,7.2500,S,Third,NaN,True,NaN,Southampton,no,False,2027-04-26
1,1,1,female,38.0,1,0,71.2833,C,First,NaN,False,C,Cherbourg,yes,False,2027-04-26

In [4]:
import pandas as pd
# string cleaning 
df2=pd.read_csv('data.csv')
df2['Name']

0                     Krish
1                    Jac  k
2                    Jo  Hn
3    muhammad yousAf   khAn
Name: Name, dtype: object

In [5]:
#removig white space 
df2['Name']=df2['Name'].str.strip()
df2['Name']

0                     Krish
1                    Jac  k
2                    Jo  Hn
3    muhammad yousAf   khAn
Name: Name, dtype: object

In [6]:
# lower case
df2['Name']=df2['Name'].str.lower()
df2['Name']

0                     krish
1                    jac  k
2                    jo  hn
3    muhammad yousaf   khan
Name: Name, dtype: object

In [7]:
# replace char 
df2['Name']=df2['Name'].str.replace('_','')
df2['Name']
df2

                     Name  Age
0                   krish   32
1                  jac  k   34
2                  jo  hn   31
3  muhammad yousaf   khan   40

In [10]:
df2['Name'].str.contains('krish',na=False)

0     True
1    False
2    False
3    False
Name: Name, dtype: bool

In [15]:
df2['Name'].str.extract(r'(\d+)')             # regex extraction

     0
0  NaN
1  NaN
2  NaN
3  NaN

In [26]:
df=pd.read_csv('salesKaggle_data.csv')
df.head(2)

df.duplicated()
df.duplicated().sum()

df.drop_duplicates()
df.drop_duplicates(subset=['Sales_Rep','Region'])
df.drop_duplicates(keep='first').head(2)

,Product_ID,Sale_Date,Sales_Rep,Region,Sales_Amount,Quantity_Sold,Product_Category,Unit_Cost,Unit_Price,Customer_Type,Discount,Payment_Method,Sales_Channel,Region_and_Sales_Rep
0,1052,2023-02-03,Bob,North,5053.97,18,Furniture,152.75,267.22,Returning,0.09,Cash,Online,North-Bob
1,1093,2023-04-21,Bob,West,4384.02,17,Furniture,3816.39,4209.44,Returning,0.11,Cash,Retail,West-Bob

In [75]:
# remaing and drop  a column 

df=pd.read_csv('data.csv')
df

                     Name  Age
0                   Krish   32
1                  Jac  k   34
2                  Jo  Hn   31
3  muhammad yousAf   khAn   40

In [76]:
# renaming 
df.rename(columns={'Name':'name','Age':'age'},inplace=True)
df

                     name  age
0                   Krish   32
1                  Jac  k   34
2                  Jo  Hn   31
3  muhammad yousAf   khAn   40

In [77]:
# add new column 
df['roll no']=12,4,5,6
df['edu']=['martic','inter','bs','ms']
df

                     name  age  roll no     edu
0                   Krish   32       12  martic
1                  Jac  k   34        4   inter
2                  Jo  Hn   31        5      bs
3  muhammad yousAf   khAn   40        6      ms

In [79]:
# drop a column 
df.drop(columns=['roll no'])

                     name  age     edu
0                   Krish   32  martic
1                  Jac  k   34   inter
2                  Jo  Hn   31      bs
3  muhammad yousAf   khAn   40      ms

In [80]:
df.drop(columns=['edu'])

                     name  age  roll no
0                   Krish   32       12
1                  Jac  k   34        4
2                  Jo  Hn   31        5
3  muhammad yousAf   khAn   40        6

In [ ]:
# # ── Type conversion ───────────────────────────────
# df['revenue'] = df['revenue'].astype(float)
# df['units']   = df['units'].astype(int)
# df['date']    = pd.to_datetime(df['date'])  # string → datetime

# # Convert to category (saves memory for low-cardinality strings)
# df['region'] = df['region'].astype('category')

# # When astype fails (mixed "12" and "N/A" strings):
# df['price'] = pd.to_numeric(df['price'], errors='coerce')
# # errors='coerce' turns invalid values to NaN instead of crashing

# # ── String cleaning ───────────────────────────────
# df['name'] = df['name'].str.strip()          # remove whitespace
# df['name'] = df['name'].str.lower()          # lowercase
# df['name'] = df['name'].str.replace('_', ' ') # replace chars
# df['name'].str.contains('Ali', na=False)     # boolean mask
# df['code'].str.extract(r'(\d+)')             # regex extraction

# # ── Duplicates ────────────────────────────────────
# df.duplicated()                # True/False per row
# df.duplicated().sum()          # count of duplicates
# df.drop_duplicates()           # remove all duplicate rows
# df.drop_duplicates(subset=['name', 'date'])  # based on specific cols
# df.drop_duplicates(keep='last')              # keep last occurrence

# # ── Rename & drop columns ─────────────────────────
# df.rename(columns={'rev': 'revenue', 'qty': 'units'}, inplace=True)
# df.drop(columns=['useless_col', 'temp'], inplace=True)

Filtering & Sorting
===
Query your data like a database — get exactly the rows you need, in the right order.

In [3]:
df=pd.read_csv('students.csv')

In [11]:
# ── Boolean filtering ─────────────────────────────
df[df['Math'] > 80]                         # high math scores
df[(df['Math'] > 80) & (df['CS'] > 90)]   # AND: both conditions
df[(df['Math'] < 60) | (df['CS'] < 60)]   # OR: either condition
df[~(df['Grade'] == 'F')].head(2)                  # NOT: negate

   StudentID           Name  Math  CS Grade region  revenue
0          1  Alice Johnson    92  95     A  North     4500
2          3    Carol White    85  88     B   East     3200

In [16]:
# # ── .query() — cleaner syntax ─────────────────────
df.query('Math > 80 and CS > 85')
df.query('Grade in ["A", "B"]').head(2)
# df.query('Math > @threshold')   # @ references a Python variable

   StudentID           Name  Math  CS Grade region  revenue
0          1  Alice Johnson    92  95     A  North     4500
2          3    Carol White    85  88     B   East     3200

In [19]:
# ── .isin() — match a list of values ──────────────
df[df['region'].isin(['North', 'South'])]
df[~df['region'].isin(['Unknown'])].head(2)  # exclude 'Unknown'

   StudentID           Name  Math  CS Grade region  revenue
0          1  Alice Johnson    92  95     A  North     4500
1          2      Bob Smith    45  78     F  South     1200

In [25]:
# ── .between() — range filter ─────────────────────
df[df['revenue'].between(100, 500)]   # inclusive

    StudentID        Name  Math  CS Grade   region  revenue
4           5  Emma Davis    55  50     F  Unknown      200
18         19  Sam Walker    35  40     F  Unknown      150

In [32]:
# # ── Sorting ───────────────────────────────────────
df.sort_values('Math')                          # ascending
df.sort_values('Math', ascending=False)        # descending
df.sort_values(['Grade', 'Math'],)             # multi-key sort
#                ascending=[True, False])
df.sort_values('Math').head(5)                # bottom 5
df.nlargest(5, 'revenue')                     # top 5 by revenue (faster)
df.nsmallest(3, 'Math')                       # 3 lowest math scores

    StudentID           Name  Math  CS Grade   region  revenue
18         19     Sam Walker    35  40     F  Unknown      150
9          10  Jack Anderson    40  45     F     East      600
1           2      Bob Smith    45  78     F    South     1200

In [ ]:
# ── Reset index after filtering ───────────────────
result = df[df['Math'] > 80].reset_index(drop=True)
# Without drop=True the old index becomes a column